### ISSUE TITLE
СПАСИБО ЧЕЛ

### ISSUE THREAD

**Issue by Lm33gtr** [hdrover/discord-drover#1]
Пашет ваще прям тютулька в тютельку!
you a Giga Chad!

**Comment by mrbean27123** [comment]
> Пашет ваще прям тютулька в тютельку! you a Giga Chad!

а что за прокси использовался? Пробовал с proxy seller, вводил в формате username:password@ip:port, то не грузится. Пробовал указывать http://username:password@ip:port и socks5://username:password@ip:port для сокс и http соответственно, тоже не работает

**Comment by Lm33gtr** [comment]
> > Пашет ваще прям тютулька в тютельку! you a Giga Chad!
> 
> а что за прокси использовался? Пробовал с proxy seller, вводил в формате username:password@ip:port, то не грузится. Пробовал указывать http://username:password@ip:port и socks5://username:password@ip:port для сокс и http соответственно, тоже не работает

там досточно указать ip:port без https://
и поставить значение ;use-nekobox-proxy = 0

**Comment by hdrover** [comment]
> > Пашет ваще прям тютулька в тютельку! you a Giga Chad!
> 
> а что за прокси использовался? Пробовал с proxy seller, вводил в формате username:password@ip:port, то не грузится. Пробовал указывать http://username:password@ip:port и socks5://username:password@ip:port для сокс и http соответственно, тоже не работает

Поддержку прокси сделал через внутренние механизмы Electron (на чем сделан дискорд) и Chrome.
Подделываю командную строку запуска и переменные окружения HTTP_PROXY и HTTPS_PROXY (просто так их не задать без dll, потому что дискорд сам запускает много вложенных процессов, которым ничего из вне не указать).
В формате ip:port точно работает. Но сомневаюсь, что получится так пустить на прокси, требующий логина и пароля (в документации у них про это написано, что какой-то баг). Можете поискать, может что найдете (у меня просто не было необходимости, не копал дальше). Начать можно отсюда:
https://www.electronjs.org/docs/latest/api/command-line-switches#--proxy-serveraddressport

> --proxy-server=address:port
> Use a specified proxy server, which overrides the system setting. This switch only affects requests with HTTP protocol, including HTTPS and WebSocket requests. It is also noteworthy that not all proxy servers support HTTPS and WebSocket requests. The proxy URL does not support username and password authentication [per Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=615947).

**Comment by jrmsk0** [comment]
просто с ip:port не работает

**Comment by hdrover** [comment]
> просто с ip:port не работает

А как работает? У меня работает именно в формате ip:port как с socks5, так и с https.

**Comment by Lezhek** [comment]
> > Пашет ваще прям тютулька в тютельку! you a Giga Chad!
> 
> а что за прокси использовался? Пробовал с proxy seller, вводил в формате username:password@ip:port, то не грузится. Пробовал указывать http://username:password@ip:port и socks5://username:password@ip:port для сокс и http соответственно, тоже не работает

Купи впс за 10 долларов на год с ракнерда и подними прокси без авторизации на нём выйдет дешевле, чем брать где-либо прокси с авторизацией.

**Comment by jrmsk0** [comment]
> > просто с ip:port не работает
> 
> А как работает? У меня работает именно в формате ip:port как с socks5, так и с https.

да чет никак не работает в том и дело) почитал тут комменты, видимо нужен такой прокси где не нужны авторизации, значит этот метод мне не подходит

**Comment by Lezhek** [comment]
> > > а что за прокси использовался? Пробовал с proxy seller, вводил в формате username:password@ip:port, то не грузится. Пробовал указывать http://username:password@ip:port и socks5://username:password@ip:port для сокс и http соответственно, тоже не работает
> > 
> > 
> > Купи впс за 10 долларов на год с ракнерда и подними прокси без авторизации на нём выйдет дешевле, чем брать где-либо прокси с авторизацией.
> 
> дешевле чем бесплатно о_о мне еще и донатить будут?) балдеж, спасибо, супер способ где еще и заплатят)

Вряд-ли бесплатные прокси у тебя когда-либо нормально заработают, тут ничего удивительного.

**Comment by jrmsk0** [comment]
> Вряд ли бесплатные прокси у тебя когда-либо нормально заработают, тут ничего удивительного.

хз, уже работают, с мая примерно, дискорд и с голосовыми тож норм. думал в этой теме еще способ будет удобный, но к сожалению мне не подошел

**Comment by hdrover** [comment]
@jrmsk0 Если еще актуально, то добавил поддержку HTTP прокси с логином и паролем

**Comment by Lezhek** [comment]
> @jrmsk0 Если еще актуально, то добавил поддержку HTTP прокси с логином и паролем

СПАСИБО ЧЕЛ
