### ISSUE TITLE
Update failed на запуске после копирования файлов в папку с Discord.exe

### ISSUE THREAD

**Issue by noobworth** [hdrover/discord-drover#10]
После обновления удалились файлы drover, при повторном их копировании и запуске Discord теперь бесконечная проверка обновлений.

![image](https://github.com/user-attachments/assets/f997bbe9-b7dc-4ac4-8a54-231daed0585b)

Версия drover: v0.6

Версия Discord:
stable 352173 (741eaa4) Host 1.0.9173 x64 (55993) Build Override: N/A Windows 10 64-bit (10.0.19045)
Electron 32.2.2
Chromium 128.0.6613.186

**Comment by Verity-Freedom** [comment]
Известная проблема.
https://github.com/hdrover/discord-drover/issues/9

**Comment by ropucyka** [comment]
> Известная проблема. #9

Ты не внимательно прочитал, это не то же самое.
У меня сегодня также не соединяется, и не обновлял ещё.

**Comment by hdrover** [comment]
Должно работать, если указан правильный прокси-сервер (тип, ip и порт). Может с сервером что-то не то? Или настройки слетели. Попробуйте воспользоваться установщиком drover.exe (который сам разместит файлы в нужной папке).

Сама функциональность точно не ломалась.

По поводу того, что иногда при выходе новой версии Discord файлы не переносятся в новую папку - это я скоро исправлю.
