### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by tomzZzey** [hdrover/discord-drover#11]
![изображение](https://github.com/user-attachments/assets/a8c413b7-ca95-4dbb-9dd7-895f1a834841)
Показывает что есть какой-то вирус

**Comment by hdrover** [comment]
В файле нет вируса. Исходные коды выложены, можно пересобрать самостоятельно. Сам механизм работы программы является довольно подозрительным, поэтому возможны ложные срабатывания (в данном случае всего лишь у одного малоизвестного антивируса из нескольких десятков). Программа внедряется в чужой процесс и перехватывает сетевые и прочие функции. Это вполне необычно, что вызывает такую реакцию.

**Comment by hdrover** [comment]
Основной код - это код именно dll. Из [drover.dpr](https://github.com/hdrover/discord-drover/blob/master/drover.dpr) из основной папки собирается version.dll. Дополнительно в папке installer есть код установщика.
