### ISSUE TITLE
Discord keeps having update faile how to fix?

### ISSUE THREAD

**Issue by Caars12349847** [hdrover/discord-drover#12]

**Comment by hdrover** [comment]
It seems that the correct proxy server is not specified in the settings. Here are two options:

1. If you want to use Discord through a proxy, you need to find a suitable proxy server and specify it in `drover.ini`.

2. If you only want to bypass the local blocking of voice calls (while keeping Discord working directly without a proxy as usual), you need to edit `drover.ini` and set the proxy parameter to an empty value, like this:

```ini
[drover]
proxy =
```
