### ISSUE TITLE
invalid host specified

### ISSUE THREAD

**Issue by rebkirb** [hdrover/discord-drover#14]
Don't need proxy. just need to bypass VC ban on discord here in the UAE
![Screenshot 2024-12-20 233214](https://github.com/user-attachments/assets/2c3ffe63-50e7-44b4-9b20-05d714b86435)

**Comment by hdrover** [comment]
Unfortunately, the installer does not currently support installation without specifying a proxy. I plan to fix this in the next version. Yes, in the UAE, a proxy is not required, but it can only be configured through manual installation. This means you need to manually copy the DLL to the folder next to Discord.exe (app-*), and set an empty value for the `proxy` parameter in `drover.ini`. 

Please let me know if everything worked for you and whether voice calls are functioning.

**Comment by rebkirb** [comment]
will do,

**Comment by rebkirb** [comment]
Thank you so much!! you finally fixed my problem

**Comment by rebkirb** [comment]
yeah works fine, thanks you're the best

**Comment by hdrover** [comment]
Great, thanks!
