### ISSUE TITLE
Возможность работы с "другими" версиями Discord

### ISSUE THREAD

**Issue by Bangtott** [hdrover/discord-drover#16]
Я юзер Discord Canary. Там раз в 5 дней точно выйдет обновление (а может и не одно), после чего слетают файлы данного проекта. Было бы круто если добавили возможность работы с другими версиями дискорда, или же самостоятельно выбирать папку для установки файлов проекта

**Comment by hdrover** [comment]
Скорее всего там разница только в имени exe файла. Несложно доработать. Попробую добавить в следующей версии.

**Comment by Bangtott** [comment]
Там разница в названии папки с дискордом и названии .exe файла
Для Discord Canary - папка DiscordCanary, исполняемый файл - с припиской .exe
Для DiscordPTB (хотя от него вроде ща смысла нет - это, если не ошибаюсь, обычный дискорд, просто сделанный под х64 системы) - папка DiscordPTB, исполняемый файл - с припиской .exe (хотя с ним я могу полностью ошибаться)
Благодарю за работу :)

**Comment by hdrover** [comment]
@Bangtott Почему-то не могу скачать Canary версию. Вроде бы жму Download на странице Canary, но получаю обычную версию.
https://canary.discord.com/
При этом PTB получил легко.

**Comment by hdrover** [comment]
Хотя поторопился написать. Все-таки нашел вот тут: https://support.discord.com/hc/en-us/articles/360035675191-Discord-Testing-Clients

**Comment by Bangtott** [comment]
Да, там чтобы её скачать нужно какие-то танцы с бубном произвести. Точно уже не помню как я её скачал. Могу отправить установщик в телеграм (хотя рисково доверять незнакомому человеку))
Если...

я уже такое сообщение настрочил)

**Comment by hdrover** [comment]
Опубликовал новый релиз, где добавил поддержку Canary и PTB.
