### ISSUE TITLE
Dll только для discord.exe без поиска некобокс и автоматическим переносом себя в апдейт папку

### ISSUE THREAD

**Issue by devintly** [hdrover/discord-drover#2]
Добрый день, можно ли использовать вашу dll в моей портативной версии дискорда с указанием авторства?  И, если у вас есть возможность, сделать версию dll только для проксирования дискорда+udp, без доп. функционала, т.к. у меня своя система обновления дискорда и не уверен, могут ли быть конфликты с текущей версией 0.2. Заранее спасибо!

**Comment by hdrover** [comment]
Значение параметра use-nekobox-proxy по умолчанию 0, то есть эта функциональность отключена, если её специально не включить. Закомментированные строчки из конфига можно удалить, ничего не изменится. Функциональность нужна для того, чтобы можно было указать в конфиге публичный прокси, но при этом использовать локальный от nekobox в случае его обнаружения. Делал просто для себя (как и всю эту dll в принципе), для массового тиражирования по сути бесполезно.

По поводу копирования файлов при обновлении - вы можете скачать версию 0.1, там этого нет. А работает примитивно. Если Discord запускает новый Discord из другой папки, где нет этой dll и конфига от него, то в новую папку копируются эти 2 файла. Сломает это что-то в вашем случае или нет - решайте сами.

**Comment by devintly** [comment]
Спасибо за ответ👍
