### ISSUE TITLE
Проблема с войс-чатом

### ISSUE THREAD

**Issue by saberkovich** [hdrover/discord-drover#3]
![image](https://github.com/user-attachments/assets/1d674c2d-529b-47a7-bf01-5f4b54c5b5f0)
Постоянное подключение к RTC, при чем если перезаходить кучу раз то в какой то момент зайти получится. Я не знаю с чем это связано, прошу помощи.

**Comment by Stranni15k** [comment]
Насколько я понимаю, данный софт позволяет через прокси обходить весь TCP трафик, такой как загрузка обновлений, картинок и т.д. А голосовые звонки идут через UDP, и программа позволяет путать траффик и пробивать маршрут в некоторых случаях, по всей видимости, иногда ей это не получается, поэтому возникает такая проблема, что возможно заработает не с первого раза. Думаю тут нужно смириться или попытаться в настройках канала поменять регион сервера :)

**Comment by hdrover** [comment]
Обход блокировки голосовых звонков сделан под конкретный DPI. К сожалению, не везде работает. И при блокировке по IP он тоже не работает. Но в большинстве случаев этого достаточно.

Попробуйте вот эту версию для интереса: https://github.com/hdrover/discord-drover/releases/tag/v0.2
Мало ли что-то сломалось в самой последней.

**Comment by hdrover** [comment]
Если сможете прислать лог трафика в Wireshark (udp), то попробую разобраться в чем дело.
Вот эта программа: https://www.wireshark.org/

**Comment by saberkovich** [comment]
> Если сможете прислать лог трафика в Wireshark (udp), то попробую разобраться в чем дело. Вот эта программа: https://www.wireshark.org/

Сделал лог
[discord_log.pcapng.gz](https://github.com/user-attachments/files/17650701/discord_log.pcapng.gz)

**Comment by hdrover** [comment]
Спасибо! Видно, что специальный пакет для обхода блокировки отправляется, то есть код работает. Но почему-то это не помогает.

Вы говорите, что иногда голос всё-таки подключается (с какой-то попытки)? А без DLL вообще никогда не подключается? Или тоже с какой-то попытки?

Еще странно, что IP соединения 35.215.138.109 Google Cloud в Гонконге, а не в какую-то сеть Дискорда (более привычно).

**Comment by saberkovich** [comment]
> Спасибо! Видно, что специальный пакет для обхода блокировки отправляется, то есть код работает. Но почему-то это не помогает.
> 
> Вы говорите, что иногда голос всё-таки подключается (с какой-то попытки)? А без DLL вообще никогда не подключается? Или тоже с какой-то попытки?
> 
> Еще странно, что IP соединения 35.215.138.109 Google Cloud в Гонконге, а не в какую-то сеть Дискорда (более привычно).

Да, иногда подключиться удаётся и тогда все нормально (Во время нахождения в войс-чате, до перезахода), смена регионов войс чата не помогает.

В плане без DLL? С режимом системного прокси в NekoRay идёт же только TCP трафик, но с TUN модом все работает без проблем.

Не знаю с чем связаны подключения IP к Google Cloud в Гонконге, я живу в Екатеринбурге, может это связано 🤷‍♂️.

**Comment by saberkovich** [comment]
А, и проблемы наблюдаются и со стримами, точно такие же, запускаются только спустя несколько попыток.

**Comment by Lezhek** [comment]
У меня  первые дни пока вышел drover работало как часы, сейчас в Войс заходит спустя некоторое время или количество попыток то же самое и относится к стрима. Возможно подкручивают ТПСУ.

**Comment by saberkovich** [comment]
Вряд-ли ТСПУ, че то провайдеры с DPI шаманят

**Comment by Lezhek** [comment]
> Вряд-ли ТСПУ, че то провайдеры с DPI шаманят

Так DPI и занимается ТПСУ и к черным ящикам у провайдеров доступа нет, кроме как включить и выключить, разве не так?

**Comment by hdrover** [comment]
> В плане без DLL? С режимом системного прокси в NekoRay идёт же только TCP трафик, но с TUN модом все работает без проблем.

Я имею в виду, что в режиме системного прокси (без TUN) реально ли зайти в голос без drover (version.dll) после нескольких попыток? Или тогда вообще никак не зайти? То есть даёт ли сейчас что-то этот обход? Если что-то даёт (без него зайти абсолютно невозможно), то я попробую его доработать. Если он вообще никак не влияет, то буду думать в другую сторону.

**Comment by saberkovich** [comment]
> > В плане без DLL? С режимом системного прокси в NekoRay идёт же только TCP трафик, но с TUN модом все работает без проблем.
> 
> Я имею в виду, что в режиме системного прокси (без TUN) реально ли зайти в голос без drover (version.dll) после нескольких попыток? Или тогда вообще никак не зайти? То есть даёт ли сейчас что-то этот обход? Если что-то даёт (без него зайти абсолютно невозможно), то я попробую его доработать. Если он вообще никак не влияет, то буду думать в другую сторону.

Теперь понял, я потестирую и отпишу.

**Comment by saberkovich** [comment]
> > В плане без DLL? С режимом системного прокси в NekoRay идёт же только TCP трафик, но с TUN модом все работает без проблем.
> 
> Я имею в виду, что в режиме системного прокси (без TUN) реально ли зайти в голос без drover (version.dll) после нескольких попыток? Или тогда вообще никак не зайти? То есть даёт ли сейчас что-то этот обход? Если что-то даёт (без него зайти абсолютно невозможно), то я попробую его доработать. Если он вообще никак не влияет, то буду думать в другую сторону.

Потестировал, без drover вообще не получается подключиться.

**Comment by hdrover** [comment]
> Потестировал, без drover вообще не получается подключиться.
Попробуйте, пожалуйста, вот с этой тестовой версией. Один вариант проверить (добавил второй пакет и задержку). Если не сработает, то есть еще другая идея.
[version.zip](https://github.com/user-attachments/files/17686324/version.zip)

**Comment by ropucyka** [comment]
Предлагаю вынести настройку обхода для UDP в конфиг, с одним-двумя полным примером. Без указания тех стратегий, которые вшиты.
И спасибо кстати.

**Comment by hdrover** [comment]
> Предлагаю вынести настройку обхода для UDP в конфиг, с одним-двумя полным примером. Без указания тех стратегий, которые вшиты.
> И спасибо кстати.

Спасибо. Со стратегиями проблема в том, что самая простая работает у меня и всех моих знакомых из разных городов. Я бы и другие добавил, но их не проверить, а добавлять наобум странно (можно очень много чего придумать). Выше saberkovich пожаловался, что работает через раз, я сделал тестовую версию (с одним предположением), но, к сожалению, он не ответил. Если бы это сработало, то уже можно было бы вынести в настройку (что является хорошей идеей). В общем, без подопытных и реальных случаев не обойтись :(

**Comment by saberkovich** [comment]
> > Предлагаю вынести настройку обхода для UDP в конфиг, с одним-двумя полным примером. Без указания тех стратегий, которые вшиты.
> > И спасибо кстати.
> 
> Спасибо. Со стратегиями проблема в том, что самая простая работает у меня и всех моих знакомых из разных городов. Я бы и другие добавил, но их не проверить, а добавлять наобум странно (можно очень много чего придумать). Выше saberkovich пожаловался, что работает через раз, я сделал тестовую версию (с одним предположением), но, к сожалению, он не ответил. Если бы это сработало, то уже можно было бы вынести в настройку (что является хорошей идеей). В общем, без подопытных и реальных случаев не обойтись :(

Сегодня ближе к ночи потестирую, просто занят я)
Если нужен подопытный то лучше мне в Telegram написать, я в гитхаб изредка захожу. Мой тег в TG: @saberkovich.

**Comment by ropucyka** [comment]
> > > Предлагаю вынести настройку обхода для UDP в конфиг, с одним-двумя полным примером. Без указания тех стратегий, которые вшиты.
> > > И спасибо кстати.
> > 
> > 
> > Спасибо. Со стратегиями проблема в том, что самая простая работает у меня и всех моих знакомых из разных городов. Я бы и другие добавил, но их не проверить, а добавлять наобум странно (можно очень много чего придумать). Выше saberkovich пожаловался, что работает через раз, я сделал тестовую версию (с одним предположением), но, к сожалению, он не ответил. Если бы это сработало, то уже можно было бы вынести в настройку (что является хорошей идеей). В общем, без подопытных и реальных случаев не обойтись :(
> 
> Сегодня ближе к ночи потестирую, просто занят я) Если нужен подопытный то лучше мне в Telegram написать, я в гитхаб изредка захожу. Мой тег в TG: @saberkovich.

Алё друг, ты выглядишь ненадёжным. Где результаты, Лебовски?

**Comment by Aler42** [comment]
> > Потестировал, без drover вообще не получается подключиться.
> 
> Попробуйте, пожалуйста, вот с этой тестовой версией. Один вариант проверить (добавил второй пакет и задержку). Если не сработает, то есть еще другая идея. [version.zip](https://github.com/user-attachments/files/17686324/version.zip)

У меня сегодня утром обычная 0.3 перестала работать. А эта заработала. Спасибо!

**Comment by saberkovich** [comment]
> > > > Предлагаю вынести настройку обхода для UDP в конфиг, с одним-двумя полным примером. Без указания тех стратегий, которые вшиты.
> > > > И спасибо кстати.
> > > 
> > > 
> > > Спасибо. Со стратегиями проблема в том, что самая простая работает у меня и всех моих знакомых из разных городов. Я бы и другие добавил, но их не проверить, а добавлять наобум странно (можно очень много чего придумать). Выше saberkovich пожаловался, что работает через раз, я сделал тестовую версию (с одним предположением), но, к сожалению, он не ответил. Если бы это сработало, то уже можно было бы вынести в настройку (что является хорошей идеей). В общем, без подопытных и реальных случаев не обойтись :(
> > 
> > 
> > Сегодня ближе к ночи потестирую, просто занят я) Если нужен подопытный то лучше мне в Telegram написать, я в гитхаб изредка захожу. Мой тег в TG: @saberkovich.
> 
> Алё друг, ты выглядишь ненадёжным. Где результаты, Лебовски?

братиш, я работаю и времени нет, с тг бы было побыстрее (Или по почте **sabernull@yandex.ru**), на гитхабе не сижу опять же скажу.



> > Потестировал, без drover вообще не получается подключиться.
> 
> Попробуйте, пожалуйста, вот с этой тестовой версией. Один вариант проверить (добавил второй пакет и задержку). Если не сработает, то есть еще другая идея. [version.zip](https://github.com/user-attachments/files/17686324/version.zip)

Да, с этой версией действительно без проблем присоединило.

**Comment by hdrover** [comment]
Здорово, спасибо. Добавил этот обход в последний релиз, но чуть уменьшил задержку. Надеюсь, с меньшей задержкой тоже работает.
