### ISSUE TITLE
MAC OS

### ISSUE THREAD

**Issue by PavelBerkut** [hdrover/discord-drover#4]
Есть ли способ портировать это решение для MAC OS ?

**Comment by Hint-ru** [comment]
К сожалению, нет. Оно сильно завязано на Windows. Под Mac по-моему можно просто запустить Discord с параметром `--proxy-server`, и вроде бы будет работать. Но я не проверял, стоит попробовать. На Windows это не работает из-за отдельного процесса обновления, который не использует этот параметр.

**Comment by hdrover** [comment]
К сожалению, нет. Оно сильно завязано на Windows. Под Mac по-моему можно просто запустить Discord с параметром --proxy-server, и вроде бы будет работать. Но я не проверял, стоит попробовать. На Windows это не работает из-за отдельного процесса обновления, который не использует этот параметр.

**Comment by Lezhek** [comment]
> К сожалению, нет. Оно сильно завязано на Windows. Под Mac, по-моему, можно просто запустить Discord с параметром `--proxy-server`, и вроде бы будет работать. Но я не проверял, стоит попробовать. На Windows это не работает из-за отдельного процесса обновления, который не использует этот параметр.

всё равно будут проблемы с войсом и медия, наверное из-за UDP
