### ISSUE TITLE
Проблема с работой фикса

### ISSUE THREAD

**Issue by MINTY161** [hdrover/discord-drover#5]
Поставил всё по инструкции, закинул файлы в папку с exe диса, но ничего не меняется, дс вообще не запускается как и раньше, попробовал поставить другой адрес прокси, но и это не принесло никакого положительного эффекта

**Comment by hdrover** [comment]
Discord зависает на обновлении? Настройки прокси правильные указали в ini? Несколько минут назад опубликовал новую версию с установщиком.

**Comment by MINTY161** [comment]
дальше обновления не проходит

**Comment by hdrover** [comment]
Что в настройках указали? Прокси-сервер есть какой-то? Без прокси-сервера это всё не работает.

**Comment by MINTY161** [comment]
новую версию поставил ничего не поменялось
прокси пробую разные бесплатные, но ничего не меняется

**Comment by MINTY161** [comment]
ещё в новой версии при нажатии кнопки install, выдаёт ошибку
![image](https://github.com/user-attachments/assets/c545dc03-0a1a-48a8-b452-bfff35f6c988)

**Comment by hdrover** [comment]
Не может скопировать version.dll в нужную папку. Возможно, файл каким-то процессом занят (Discord закрыть или Windows перезагрузить).

**Comment by MINTY161** [comment]
дс закрыт попробую перезагрузить

**Comment by MINTY161** [comment]
перезагрузка не помогла, от админа тоже нет

**Comment by MINTY161** [comment]
и у меня все файлы из папки  уже в папке drover уже в корне

**Comment by Stranni15k** [comment]
> перезагрузка не помогла, от админа тоже нет

Проверь через диспетчер задач открытые процессы Discord возможно там висит какой-то процесс, у него бывает такое

**Comment by MINTY161** [comment]
> > перезагрузка не помогла, от админа тоже нет
> 
> Проверь через диспетчер задач открытые процессы Discord возможно там висит какой-то процесс, у него бывает такое

не пусто

**Comment by MINTY161** [comment]
ну файлы дровера я выкинул из корня, и ошибка с фото ушла, но вот прокси никакие чёт не работают

**Comment by Lezhek** [comment]
попробуй убрать из автозагрузки дискорд и ребут сделать, у меня такое бывало частенько

**Comment by MINTY161** [comment]
дс не в автозагрузке

**Comment by MINTY161** [comment]
с проблемами разобрался, только прокси не находилось нормальных, всем спасибо за помощь
