### ISSUE TITLE
Не работает с версией 1.0.9034 на Win7

### ISSUE THREAD

**Issue by afjback** [hdrover/discord-drover#7]
При запуске с проводника молча завершается, при запуске с консоли выдаёт:
Discord.exe: invalid option -- `-p'
Try 'Discord.exe --help' for more information.
[4608:1126/181646.873:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: ╩рэры с√ы чръЁ√Є.(0x6D)
Discord 1.0.9034

и тоже завершается

**Comment by hdrover** [comment]
У вас последняя версия 0.5? Что в drover.ini указано? Какие-то свои дополнительные параметры дискорду не передаете?

**Comment by afjback** [comment]
Версия 0.5

```[drover]
; Proxy can use http or socks5 protocols
;proxy = http://127.0.0.1:1080
proxy = socks5://127.0.0.1:9050

;use-nekobox-proxy = 1
;nekobox-proxy = http://127.0.0.1:2080
```
Доппраметров нет, просто запускаю discord.exe из %localappdata%\discord\app-1.0.9034

Discord x64 (подменяемая библиотека version.dll 64-битная, и 32-битное приложение её просто не увидит)

**Comment by hdrover** [comment]
Мне несложно сделать еще одну dll для 32 бит, по сути только при сборке переключить. Просто не выкладывал, так как не знал, что такими еще кто-то пользуется (вроде бы дискорд сейчас поддерживает только 64).
Значит какая-то несовместимость именно с Windows 7. Я разберусь в чем дело и попробую исправить на днях.

**Comment by afjback** [comment]
Последние версии для вин7:
х32 1.0.903**6**
х64 1.0.903**4**

**Comment by hdrover** [comment]
@afjback Проверьте, пожалуйста. Вроде бы исправил в последнем релизе (0.6). И спасибо за ссылки.
https://github.com/hdrover/discord-drover/releases/tag/v0.6

**Comment by afjback** [comment]
Сам по себе работает.

Если в фоне запущен Proxifier pe, даже с отключённым правилом на дискорд, то вылетает диалог:
---------------------------
Proxifier PE Error (64-bit subsystem)
---------------------------
C:\Users\2\AppData\Local\Discord\app-1.0.9034\Discord.exe

Error: Cannot decode instructions at 7FEFF381BD0 : 5, function 1, location 0
Code: E9 2B E4 6 0 48 89 74 24 20 89 54 24 10 89 4C 24 8 57 41 54 41 55 41 56 41 57 48 83 EC 

Please try to change hook type to "Module Copy" at Profile->Advanced->Proxification_Engine (64-bit) menu of Proxifier.
---------------------------
ОК   
---------------------------

Стояли значения по умолчанию:
intercept network call at ws2_32.dll
hook type Function prologue copy

При переключении на Module copy Дискорд не запускается, с консоли выдаёт:

Discord.exe: invalid option -- `-p'
Try 'Discord.exe --help' for more information.
[5924:1127/175348.516:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: ╩рэры с√ы чръЁ√Є.(0x6D)
Discord 1.0.9034
Starting app.
Starting updater.
Determined current Windows architecture: x64
splashScreen.initSplash(false)
blackbox: 2024-11-27T14:53:48.882Z 0
----------------------------------------------
blackbox: 2024-11-27T14:53:48.916Z 1 Discord starting: {"newUpdater":true,"releaseChannel":"stable",
"version":"1.0.9034"}, modulepath: C:\Users\2\AppData\Roaming\discord\module_data
blackbox: 2024-11-27T14:53:48.920Z 2 тЬЕ webContents.created web1 ""
blackbox: 2024-11-27T14:53:48.927Z 3 тЬЕ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight тАФ Loading Discord' ]
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
[5924:1127/175349.091:ERROR:crashpad_client_win.cc(142)] crash server failed to launch, self-terminating
[3228:1127/175349.132:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.

**Comment by hdrover** [comment]
Я правильно понял, что без Proxifier теперь программа работает нормально, направляет дискорд на прокси?
Proxifier какая версия?

**Comment by afjback** [comment]
Да, если proxifier выгрузить, дискорд "самостоятельно" работает через прокси.

Proxifier Portable Edition v4.12

**Comment by hdrover** [comment]
Да, с PE у меня тоже не заработало на базовых настройках. В первый раз проверил на обычной версии (с ней всё нормально, но у неё и переключения режимов нет, другой принцип).

Но версия PE заработала с mswsock.dll в режиме "function prologue copy".

Дело в том, что drover тоже ставит хуки на сетевые функции через jmp (E9) как раз в библиотеке ws2_32.dll. Proxifier поверх них не может поставить свои. Ругается как раз на код, который начинается с этой инструкции ("Code: E9").
