### ISSUE TITLE
Слетает после каждого обновления DIscord

### ISSUE THREAD

**Issue by ma3uk** [hdrover/discord-drover#9]
На 2ух ПК почему-то слетает Discord-drover после каждого обновления, т.е. он не переносится на новую версию, с чем может быть такое связано? При этом на других 2ух ПК drover без проблем переносится и работает. 
Каких-либо значимых отличий между ПК, на которых работает и не работает автоперенос, не выявил, везде отключен антивирус, везде Discord установлен в пользовательскую папку на диске C:, везде имя пользователя на латинице

**Comment by hdrover** [comment]
Везде одинаковая версия? В самой первой версии 0.1 не было переноса файлов, добавил только в 0.2. Но мне тоже показалось, что в последний раз у меня не перенеслось (а может я сам удалил, когда что-то тестировал, и не заметил). Попробую разобраться.

**Comment by hdrover** [comment]
Между папками он точно переносится, но, возможно, в каких-то ситуациях что-то ломается.
https://github.com/hdrover/discord-drover/blob/master/drover.dpr#L174
Там условия, что имя файла текущего процесса - Discord.exe, имя запускаемого файла - Discord.exe, что в старой папке есть drover.ini и version.dll, что в новой папке нет drover.ini и version.dll.
Сейчас скачал предыдущую версию, всё хорошо перенеслось.

Может у дискорда есть разные механизмы обновления? Например, когда он выключен, и когда он запущен.

**Comment by Lezhek** [comment]
То же самое происходит.

**Comment by hdrover** [comment]
Не, должно работать. Но я не могу определить причину на данный момент. Жду очередного обновления, чтобы сломалось, чтобы залогировать в чем дело. И исправлю после этого.

**Comment by Verity-Freedom** [comment]
> Не, должно работать. Но я не могу определить причину на данный момент. Жду очередного обновления, чтобы сломалось, чтобы залогировать в чем дело. И исправлю после этого.

У меня портативный Тор, я использую сборку Запрета для разблокировки Дискорд. Тор создаёт socks5 на 127.0.0.1:9050. Если пофиксишь слетание проги, можно будет использовать дровер вместо запрета, ибо тор бесплатный плюс его никто не заблочит. Также в чатике услышал что есть очень похожее [решение ](https://github.com/runetfreedom/discord-voice-proxy) discord voice proxy и тоже для socks5 (для Тора, essentially), у него уже вроде ничего не слетает.

**Comment by Verity-Freedom** [comment]
@hdrover Тор в udp не может так что считаю твой способ очень перспективным но слетание апдейтов обязательно нужно пофиксить.

**Comment by Verity-Freedom** [comment]
@hdrover в очередной раз слетело.
https://github.com/hdrover/discord-drover/issues/10

**Comment by Verity-Freedom** [comment]
Ждём фикса.

**Comment by hdrover** [comment]
На одном компьютере удалось залогировать. Похоже дело в том, что если обновление выходит при работающем дискорде, то это обновление скачивается в фоне. А запущена новая версия будет при следующем запуске дискорда через updater. Такие ситуации не обрабатываются нормально. Жаль, что нельзя дополнительную информацию получить, не дожидаясь нового обновления (

**Comment by hdrover** [comment]
Всё, дождался очередного обновления. Новая версия успешно перенесла вовремя все файлы. Сегодня или завтра опубликую новый релиз.

**Comment by Verity-Freedom** [comment]
Очень жду.

**Comment by Verity-Freedom** [comment]
@hdrover не возникло проблем?

Очень хочу протестировать но уже в пофикшенной версии ибо баг довольно критический.

**Comment by hdrover** [comment]
Всё, загрузил релиз. Надеюсь, у всех будет работать. Способ решения довольно костыльный, но вроде бы его достаточно.

Проблема в том, чтобы обнаружить, что появилась папка с новой версией. Можно по таймеру мониторить, можно хукать новые функции WinAPI (например, создание папки), но не хотелось заморачиваться. Дискорд после фонового обновления запускает reg.exe для операций с реестром. Действие кажется неочевидным и бессмысленным, но оно есть. А запуск процессов уже отслеживается, поэтому легко было триггером для копирования использовать именно это событие.
